# Generated by Django 4.2.7 on 2023-12-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
